### ISSUE TITLE
Scrape and store Rental Registration

### ISSUE THREAD

**Issue by ludstuen90** [ludstuen90/ohio#55]
In warren county, this means looking at "Owner Occupied" field. Ensure our system acknowledges that our "renter occupied" field is scraping from an "owner occupied" field, which might mean something else. (This will involve updating our docs).

**Comment by ludstuen90** [comment]
@walinchus 
Confirming based on our <a href="https://github.com/ludstuen90/ohio/issues/4">earlier conversation here</a> that for Warren county, we'll use the 'owner occupied' field to generate the `rental_registration` field.

I'll add a disclaimer saying that this field indicates it's likely a rental property, but other situations could exist.

How's this sound? (Unless you know of a better place to check online for more definitive). Looks like rental properties in Ohio are required to register with the county one time ... and I don't see a lot of records online.

**Comment by walinchus** [comment]
Well I would keep the name "owner occupied" but then yes in the disclaimer
I would say it usually indicates a rental property.

**Comment by ludstuen90** [comment]
OK sounds good, I can change this column name from 'rental_registration' to 'owner_occupied'.

Looks like for other counties, we'll often be calculating this based on whether an owner gets a tax credit or not. 

Thanks!
