### ISSUE TITLE
Warren County: Unable to pull sale dates when multiple buildings

### ISSUE THREAD

**Issue by ludstuen90** [ludstuen90/ohio#70]
We're unable to pull sales dates when a record includes multiple buildings.

This information exists, we'll just have to navigate to the "Sales History" page. 

Creating a separate issue for this to add as enhancement later.

**Comment by ludstuen90** [comment]
This became even more important because we'll need to validate a mortgage has to do with a current owner. 

IE: Currently, if we don't store a date sold, we can't store mortgage information (even if it exists)

More justification to fix this! (See `identify_most_recent_mortage_for_each()` )

**Comment by walinchus** [comment]
Also, just FYI, the date of the mortgage is the closing date, which might be slightly different from the recording date.

**Comment by ludstuen90** [comment]
Ah, that's a good point! Do you think we'd need this distinction? Or is an apprx. date close enough? I could add a note to the field

**Comment by ludstuen90** [comment]
Closed with PR
